export const POLAROIDS = [
  {
    id: 1,
    title: "The Old Oak",
    image: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=300&q=80",
    tags: ["Nature", "Flora", "Botany"],
    x: 80, y: 80,
    description: "Witnesses report seeing a figure near the old oak at dusk. The tree stands at the edge of Millfield Estate, a landmark since 1842.",
    connections: [2, 3],
    rotation: -4,
    pinColor: "#c0392b",
  },
  {
    id: 2,
    title: "Abandoned Warehouse",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&q=80",
    tags: ["Urban", "Architecture", "Industrial"],
    x: 430, y: 55,
    description: "Tire tracks found leading into the warehouse. Security footage shows a vehicle entering at 11:47 PM on the night in question.",
    connections: [4],
    rotation: 3,
    pinColor: "#1a6b3a",
  },
  {
    id: 3,
    title: "Rainy Street",
    image: "https://images.unsplash.com/photo-1515474594679-6a66b7fdcbe4?w=300&q=80",
    tags: ["Urban", "Weather", "Nocturnal"],
    x: 200, y: 300,
    description: "Street cameras captured a person of interest on this corner at 10:15 PM. Rain obscured facial features but clothing is distinctive.",
    connections: [5],
    rotation: -2,
    pinColor: "#154f8a",
  },
  {
    id: 4,
    title: "Coastal Cliffs",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=300&q=80",
    tags: ["Nature", "Geology", "Maritime"],
    x: 570, y: 250,
    description: "A briefcase matching the description was found wedged in a crevice. Forensics confirm it was placed there, not fallen.",
    connections: [5],
    rotation: 5,
    pinColor: "#7b3a0e",
  },
  {
    id: 5,
    title: "The Diner",
    image: "https://images.unsplash.com/photo-1555992336-03a23c7b20ee?w=300&q=80",
    tags: ["Urban", "Commerce", "Social"],
    x: 350, y: 380,
    description: "Last confirmed sighting at this diner. Waitress recalls a heated argument between two men over an envelope. One paid cash and left in a hurry.",
    connections: [],
    rotation: -3,
    pinColor: "#c0392b",
  },
];
