import { logger } from '../utils/logger.js';

/**
 * Service to handle Server-Sent Events (SSE) streaming of LLM responses to the client.
 */
export const StreamService = {
  /**
   * Pipes an Ollama streaming response into an Express SSE response.
   * @param {import('express').Response} res - Express response object.
   * @param {import('stream').Readable} llmStream - Readable stream from Ollama.
   * @param {function} [onDoneCallback] - Optional callback function invoked when stream is fully consumed.
   */
  handleSSEStream(res, llmStream, onDoneCallback) {
    // 1. Establish SSE headers
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    res.setHeader('X-Accel-Buffering', 'no'); // Disable buffering for Nginx/reverse proxies
    res.flushHeaders();

    let accumulatedText = '';
    let buffer = '';

    // Handle incoming data chunks
    const onData = (chunk) => {
      buffer += chunk.toString();
      const lines = buffer.split('\n');
      buffer = lines.pop() || ''; // Save trailing partial line back to buffer

      for (const line of lines) {
        if (!line.trim()) continue;
        try {
          const parsed = JSON.parse(line);
          const token = parsed.response || '';
          
          if (token) {
            accumulatedText += token;
            // Write token payload
            res.write(`data: ${JSON.stringify({ token })}\n\n`);
          }

          if (parsed.done) {
            // Stream complete according to Ollama payload
            handleStreamComplete();
          }
        } catch (err) {
          // JSON parse failed, could be partial line, ignore and let buffer handle it
        }
      }
    };

    // Handle stream end/close
    const onEnd = () => {
      // In case we ended without a formal done message
      handleStreamComplete();
    };

    // Handle client disconnect
    res.on('close', () => {
      logger.info('Client closed SSE connection. Cleaning up stream listeners.');
      cleanup();
    });

    const cleanup = () => {
      llmStream.removeListener('data', onData);
      llmStream.removeListener('end', onEnd);
      llmStream.removeListener('error', onError);
    };

    const onError = (error) => {
      logger.error('Error occurred in Ollama stream', error);
      res.write(`data: ${JSON.stringify({ error: 'LLM stream error: ' + error.message })}\n\n`);
      res.end();
      cleanup();
    };

    let streamCompleted = false;
    const handleStreamComplete = () => {
      if (streamCompleted) return;
      streamCompleted = true;
      
      cleanup();

      logger.success('Ollama stream completed. Parsing related topics...');
      const relatedTopics = parseRelatedTopics(accumulatedText);
      logger.info(`Extracted related topics: ${JSON.stringify(relatedTopics)}`);

      // Write related topics
      res.write(`data: ${JSON.stringify({ relatedTopics })}\n\n`);
      // Write termination signal
      res.write('data: [DONE]\n\n');
      res.end();

      if (onDoneCallback) {
        onDoneCallback(accumulatedText, relatedTopics);
      }
    };

    llmStream.on('data', onData);
    llmStream.on('end', onEnd);
    llmStream.on('error', onError);
  }
};

/**
 * Extracts related topics from the Markdown response generated by the LLM.
 * Looks for header block and bullet points.
 * @param {string} text - Full accumulated LLM response text.
 * @returns {string[]} - Array of related topics.
 */
function parseRelatedTopics(text) {
  if (!text) return [];

  const relatedTopics = [];
  // Use regex to locate heading for related topics (supporting variations)
  const pattern = /(?:### Related Exploration Paths|Related Topics|Related Exploration Paths)\s*\n([\s\S]*)/i;
  const match = text.match(pattern);

  if (match && match[1]) {
    const listContent = match[1];
    // Match line-by-line bullet points (e.g. "- Topic Name" or "* Topic Name")
    const bulletMatches = listContent.matchAll(/(?:^|\n)[-*]\s*([^\n]+)/g);
    for (const bm of bulletMatches) {
      let topic = bm[1].trim();
      // Clean markdown bold, italic, links, brackets, and code tags
      topic = topic.replace(/[*_`\[\]]/g, '').trim();
      if (topic && relatedTopics.length < 5) {
        relatedTopics.push(topic);
      }
    }
  }

  // Fallback: If no structured block was found or matched, try to extract a few CAPITALIZED nouns or similar,
  // or return default related pathways based on context if needed. Let's return empty if not found so the frontend
  // knows it failed, but let's make it robust to heading detection.
  return relatedTopics;
}
